; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "ShowDeck"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "iSophes"
#define MyAppURL "https://isophes.com"
#define MyAppExeName "ShowDeck.exe"
#define MyAppAssocName MyAppName + " Project"
#define MyAppAssocExt ".showdeck"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E00FBB71-A4C8-4692-A2F1-C656A12B09E2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=showdeck-installer
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\src-tauri\target\release\{#MyAppExeName}"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstapp.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstaudioconvert.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstaudiomixer.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstaudioparsers.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstaudioresample.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstautodetect.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstcoreelements.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstdirectsound.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstflac.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstisomp4.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstmpg123.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstogg.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstopus.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstplayback.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gsttypefindfunctions.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstvolume.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstvorbis.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstwasapi.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\lib\gstwasapi2.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\ffi-7.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\FLAC-8.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gio-2.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\glib-2.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gmodule-2.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gobject-2.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gstbase-1.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gstreamer-1.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\gthread-2.0-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\intl-8.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\mp3lame-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\ogg-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\opus-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\pcre2-8-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
Source: "C:\Users\Sophie\Documents\Computer Science\NEA\ShowDeck\dlls\bin\vorbis-0.dll"; DestDir: "{app}\lib\gstreamer-1.0"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKLM; Subkey: "SOFTWARE\GStreamer\1.0"; ValueType: string; ValueName: "SystemPluginsPath"; ValueData: "{app}\lib\gstreamer-1.0"; Flags: createvalueifdoesntexist uninsdeletekey

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

